# Site settings
title: ANDREW "AJ" JONES
description: "Software Development Consultant."
baseurl: ""
url: "http://andy-c-jones.github.io"
twitter_username: andy_c_jones
github_username:  andy-c-jones

# Build settings
markdown: kramdown
permalink: pretty
