# Site settings
title: Andrew "AJ" Jones
description: "The personal site for Andrew 'AJ' Jones, Software Development Consultant."
baseurl: ""
url: "http://andy-c-jones.github.io"
twitter_username: andy_c_jones
github_username:  andy-c-jones

# Build settings
markdown: kramdown
permalink: pretty
